#!/bin/bash

cd $1

if [ ! -d .git ]
then
	echo ERROR: $1/.git not found! >&2
	exit 1
fi

git tag
if [[ $? > 0 ]]
then
	exit $?
fi

echo
echo -n "New Tag name: "
read -r tag

echo -n "Add the Tag $tag and push it to `git config --get remote.origin.url`? [y/N] "
read -r response
if [[ $response =~ ^([yY])$ ]]
then
    git tag $tag
    git push --tags
else
    echo aborted >&2
    exit 1
fi
